name: CI
on: [pull_request, push]
jobs:
  mix_test:
    name: mix test (Elixir ${{ matrix.elixir }} OTP ${{ matrix.otp }})
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        elixir: [1.15.8, 1.16.3, 1.17.3, 1.18.1]
        otp: [25.3, 26.2, 27.1]
        exclude:
          - elixir: 1.15.8
            otp: 27.1
          - elixir: 1.16.3
            otp: 27.1
    env:
      MIX_ENV: test
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}
          experimental-otp: true
      - run: |
          mix local.hex --force
          mix local.rebar --force
          mix deps.get
      - run: mix coveralls.github
