name: CI
on: [pull_request, push]
jobs:
  mix_test:
    name: mix test (Elixir ${{ matrix.elixir }} OTP ${{ matrix.otp }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        elixir: [1.12.3, 1.13.4, 1.14.2]
        otp: [22.3.4.26, 23.3.4.18, 24.3.4.7, 25.2]
        exclude:
          - elixir: 1.12.3
            otp: 25.2
          - elixir: 1.14.2
            otp: 22.2.4.26
    env:
      MIX_ENV: test
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2.3.2
      - uses: actions/setup-elixir@v1
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}
      - run: |
          mix local.hex --force
          mix local.rebar --force
          mix deps.get
      - run: mix coveralls.github
